version: "3.9"

services:
  cinema_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  init_db:
    build: .
    command: python init_db.py
    depends_on:
      cinema_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@cinema_db:5432/cinema_db"

  cinema_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      init_db:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@cinema_db:5432/cinema_db"
    command: >
      sh -c "sleep 2 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: